gold/urls.py
from django.urls import path
from django.http import HttpResponse
#from django.contrib.auth.views import LoginView, LogoutView

from . import views


app_name = 'gold'

urlpatterns = [
    path('', views.contract_view, name='form'),
]

inventory/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

app_name = 'inventory'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('search/', views.ItemSearch.as_view(), name='item_search'),
    path('add/', views.ItemCreate.as_view(), name='create'),
    path('<int:pk>/update/', views.ItemUpdate.as_view(), name='update'),
    path('<int:pk>/delete/', views.ItemDelete.as_view(), name='delete'),
    path('inventory/add/', views.InventoryCreate.as_view(),
         name='inventory_create'),
    path('inventory/select/', views.inventory_select, name='inventory_select'),
    path('shelf/reset', views.shelf_reset, name='shelf_reset'),
    path('stats/', views.Stats.as_view(), name='stats'),
    path('latex/', views.latex, name='latex'),
    path('register/', views.register, name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

inventory/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Make, MakeGroup, Inventory, Unit, Item


class ItemForm(forms.ModelForm):
    """ Inventory item form """
        
    def __init__(self, *args, session_data=None, **kwargs):
        super().__init__(*args, **kwargs)

        qs = self.fields['make'].queryset.filter(
            group=session_data['group_id'],
        ).order_by('name')

        if not session_data['show_hidden']:
            qs = qs.exclude(is_hidden=True)

        self.fields['make'].queryset = qs
        # check if the inventory is in net prices
        net_prices = Inventory.objects.get(pk=session_data['inventory_id'])\
                                      .net_prices
        if not net_prices:
            # remove net_price field for gross only inventories
            self.fields.pop('net_price')
            self.fields['price'].widget = forms.TextInput(attrs={
                'autofocus': True})
            
    make = forms.ModelChoiceField(Make.objects.all(),
                                  label="")

    net_price = forms.CharField(label="",
                                widget=forms.TextInput(
                                    attrs={'autofocus': True,
                                           'class': 'form-number',
                                           'size': 6}))
    price = forms.CharField(label="",
                            widget=forms.TextInput(
                                attrs={'size': 6,
                                       'class': 'form-number'}))
    quantity = forms.CharField(label="",
                               widget=forms.TextInput(
                                   attrs={'size': 6,
                                          'class': 'form-number'}))
    unit = forms.ModelChoiceField(Unit.objects.all(), label="")

    field_order = ['make', 'net_price', 'price', 'quantity', 'unit']

    class Meta:
        model = Item
        fields = ['make', 'net_price', 'price', 'quantity', 'unit']
    

class InventorySelectForm(forms.Form):
    """ Inventory select form """

    inventory = forms.ModelChoiceField(queryset=Inventory.objects.all(),
                                       label="remanent")
    group = forms.ModelChoiceField(queryset=MakeGroup.objects.all(),
                                   label="dział")


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=32, label="Imię")
    last_name = forms.CharField(max_length=32, label="Nazwisko")

    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields + ('first_name', 'last_name')


class ItemSearchForm(forms.Form):
    """ Item search """

    # FIXME
    def __init__(self, *args, session_data=None, **kwargs):
        super().__init__(*args, **kwargs)

        make_ids = Item.objects\
                       .filter(inventory_id=session_data['inventory_id'])\
                       .values_list('make_id', flat=True)
        self.fields['make'].queryset = self.fields['make']\
                                           .queryset\
                                           .filter(id__in=set(make_ids))\
                                           .order_by('name')

        # check if the inventory is in net prices
        net_prices = Inventory.objects.get(pk=session_data['inventory_id'])\
                                      .net_prices
        if not net_prices:
            self.fields['net_price'].disabled = True
        
    id = forms.IntegerField(required=False, label="id",
                            widget=forms.TextInput(attrs={
                                'size': 6,
                                'autocomplete': 'off'
                            }))
    make = forms.ModelChoiceField(
        queryset=Make.objects.exclude(item__make=None),
        label="nazwa towaru",
        required=False,
        widget=forms.Select(
            attrs={'autofocus': True}))
    net_price = forms.FloatField(label="cena netto", required=False,
                                 widget=forms.TextInput(
                                     attrs={'size': 6}))
    price = forms.FloatField(label="cena brutto", required=False,
                             widget=forms.TextInput(attrs={
                                 'size': 6
                             }))
    myuser = forms.ModelChoiceField(
        queryset=User.objects.exclude(item__created_by=None),
        label="osoba",
        required=False)
    show_all = forms.BooleanField(label="wszystko", required=False)

inventory/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.edit import FormMixin
from django.db.models import Count
from django.conf import settings

from djatex import render_latex

from .models import Inventory, Item, Unit
from .forms import ItemForm, InventorySelectForm, SignUpForm
from .forms import ItemSearchForm
from .utils import shelf_counter, stats, get_total_items, sum_by_group
from .mixins import InventorySessionMixin


@staff_member_required
def latex(request):
    inventory_id = request.session.get('inventory_id')

    items = get_total_items(inventory_id)
           
    inventory = Inventory.objects.get(pk=inventory_id)

    total_sum = stats(inventory_id)
    if inventory.price_mode == 'netto':
        total_sum = total_sum['net']
    else:
        total_sum = total_sum['gross']

    file_name = "rem_nr_{id}_z_{date}.pdf".format(
        id=inventory_id,
        date=inventory._creation_date())
    
    context = {'items': items,
               'counter': items.count(),
               'total_sum': total_sum,
               'inventory': inventory,
               'date': inventory.created}
    
    return render_latex(request, file_name, 'inventory/item.tex',
                        error_template_name='inventory/error.html',
                        home_dir=settings.TEX_HOME,
                        context=context)
                                
                                    
class IndexView(LoginRequiredMixin, InventorySessionMixin, FormMixin,
                ListView):
    """ index """
    
    model = Item
    template_name = 'inventory/index.html'
    form_class = ItemForm
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['current_inventory'] = Inventory.objects.filter(
            pk=self.inventory).first()
        context['shelf_counter'] = shelf_counter(self.inventory,
                                                 self.request.user.id,
                                                 self.shelf)
        return context
                
    def get_queryset(self):
        query = Item.objects.filter(inventory=self.inventory,
                                    created_by=self.request.user)\
                                    .prefetch_related('make', 'unit')

        return query.order_by('-pk')[:5][::-1]  # reversed 5 last items

    def get_initial(self):
        try:
            last_choice = Item.objects.filter(created_by=self.request.user)\
                          .latest('pk')
        except Item.DoesNotExist:
            last_make = None
            last_unit = Unit.QTY_ID
        else:
            last_make = last_choice.make.id
            last_unit = last_choice.unit.id
            
        return {"make": last_make,
                "unit": last_unit,
                "quantity": 1}


class ItemCreate(LoginRequiredMixin, InventorySessionMixin, CreateView):
    """ add an item to the inventory """

    model = Item
    template_name = 'inventory/index.html'
    form_class = ItemForm

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.inventory_id = self.request.session['inventory_id']
        return super().form_valid(form)


class ItemUpdate(LoginRequiredMixin, InventorySessionMixin, UpdateView):
    """ update an item """

    model = Item
    template_name = 'inventory/item_update_form.html'
    form_class = ItemForm
    

class ItemDelete(LoginRequiredMixin, DeleteView):
    """ delete an item """

    model = Item
    template_name = 'inventory/inventory_confirm_delete.html'

    def get_success_url(self):
        return reverse_lazy('inventory:index')


class InventoryCreate(LoginRequiredMixin, CreateView):
    """ create an inventory session """

    model = Inventory
    fields = ['shop', 'net_prices']

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)

    
@login_required()
def inventory_select(request):
    """ select an inventory """
    template = "inventory/inventory_select.html"
    form = InventorySelectForm()
    inventories = Inventory.objects.all()

    if not inventories:
        return redirect('inventory:inventory_create')
    
    last_inventory = inventories.latest('pk')
    
    if request.POST:
        request.session['inventory_id'] = request.POST.get('inventory')
        request.session['group_id'] = request.POST.get('group')
        request.session['show_hidden'] = request.POST.get('show_hidden', False)

        return redirect('inventory:index')

    inventory = request.session.get('inventory_id', last_inventory.id)
    group = request.session.get('group_id', 1)
    form = InventorySelectForm({'inventory': inventory,
                                'group': group})

    return render(request, template, {"form": form,
                                      "inventories": inventories,
                                      "current_inventory": inventory})


class ItemSearch(LoginRequiredMixin, InventorySessionMixin, FormMixin,
                 ListView):
    """ item search """

    model = Item
    form_class = ItemSearchForm
    template_name = 'inventory/item_search.html'
    paginate_by = 50
    
    def get_queryset(self):
        query = Item.objects.filter(inventory=self.inventory)

        if self.myuser:
            query = query.filter(created_by=self.myuser)
        if self.make and self.make != '':
            query = query.filter(make=self.make)
        if self.id and self.id != '':
            query = query.filter(id=self.id)
        if self.net_price and self.net_price != '':
            query = query.filter(net_price=self.net_price)
        if self.price and self.price != '':
            query = query.filter(price=self.price)
        if not self.show_all and not self.myuser and not self.make and\
           not self.price and self.shelf:
            query = query.filter(pk__gte=self.shelf)
            query = query.filter(created_by=self.request.user.id)

        self.item_num = query.count()
        query = query.prefetch_related('unit', 'make', 'created_by')\
                     .order_by('pk')
        return query

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['current_inventory'] = Inventory.objects.filter(
            pk=self.inventory).first()
        context['shelf_counter'] = shelf_counter(self.inventory,
                                                 self.request.user.id,
                                                 self.shelf)

        context['item_num'] = self.item_num
        return context

    def get_initial(self):
        return {'make': self.make,
                'net_price': self.net_price,
                'price': self.price,
                'myuser': self.myuser}
        
    def dispatch(self, request, *args, **kwargs):
        self.id = request.GET.get('id', None)
        self.make = request.GET.get('make', None)
        self.net_price = request.GET.get('net_price', None)
        self.price = request.GET.get('price', None)
        self.myuser = request.GET.get('myuser', None)
        self.show_all = request.GET.get('show_all', None)
        
        return super().dispatch(request, *args, **kwargs)


@login_required()
def shelf_reset(request):
    """ update shelf counter """
    
    if request.session.get('inventory_id') is None:
            return redirect('inventory:inventory_select')

    last_item_id = Item.objects.filter(created_by=request.user,
                                       inventory_id=request.session.get(
                                        'inventory_id'))

    if last_item_id.exists():
        request.session['shelf_id'] = last_item_id.last().pk + 1
    else:
        request.session['shelf_id'] = 0
    
    return redirect('inventory:index')


@method_decorator(staff_member_required, name='dispatch')
class Stats(TemplateView):
    """ sums and statistics """

    template_name = 'inventory/stats.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['sum'] = stats(self.inventory)
        context['count'] = self.items.count()
        context['count_by_user'] = self.items\
                                       .values('created_by__username')\
                                       .annotate(count=Count('pk'))
        context['current_inventory'] = self.items.first().inventory
        context['sum_by_group'] = sum_by_group(self.items)
        
        return context
    
    def dispatch(self, request, *args, **kwargs):
        self.inventory = request.session.get('inventory_id')

        if not self.inventory:
            return redirect('inventory:inventory_select')

        self.items = Item.objects.filter(inventory_id=self.inventory)

        # check if there are any items
        if not self.items:
            return redirect('inventory:index')
        
        return super().dispatch(request, *args, **kwargs)


def register(request):
    """ registration form """
    
    if request.method == 'POST':
        form = SignUpForm(request.POST)

        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']

            user = authenticate(username=username,
                                password=password)
            login(request, user)

templates/inventory/base_inventory.html
{% extends 'base.html' %}
{% load static %}

{% block navbar %}

<div class="row" id="navbar">
  <div class="two columns">
    <h3>Remanent</h3>
  </div>
  <div class="ten columns">
    <ul>
      {% if request.user.is_staff %}
      <li><a href="{% url 'inventory:stats' %}">sumy</a></li>
      {% endif %}
      <li><a href="{% url 'inventory:inventory_select' %}">zmień sklep</a></li>
      <li><a href="{% url 'inventory:item_search' %}">szukaj</a></li>
      <li><a href="{% url 'inventory:shelf_reset' %}">zeruj licznik</a></li>
      <li><a href="{% url 'inventory:index' %}">pisz dalej</a></li>
    </ul>
  </div>
</div>

<div class="row" id="current_shop">
  <div class="eight columns">
    {% if current_inventory %}
    sklep: <strong>#{{ current_inventory }}</strong>
    {% endif %}
  </div>
  <div class="four columns" id="shelf_counter">
    {% if shelf_counter %}
        <a href="{% url 'inventory:item_search' %}" title="wyświetl półkę" class="">{{ shelf_counter.piece|add:shelf_counter.weight }}
            <span style="font-size: 1.1rem;">wyświetl</span>
        </a>
    {% endif %}
  </div>
</div>

{% endblock navbar %}

templates/inventory/error.html
:-( 

templates/inventory/index.html
{% extends 'inventory/base_inventory.html' %}
{% load static %}
{% block title %}remanent{% endblock %}

{% block body %}

{% if object_list %}

<table class="items">
  <tr>
    <th>id</th>
    <th>nazwa</th>
    <th>{% if object_list.0.net_price != 0 %}c. netto{% endif %}</th>
    <th>cena</th>
    <th>ilość</th>
    <th>j.m.</th>
    <th></th>
  </tr>
  
{% for item in object_list %}

<tr>
  <td><a class="item_id" href="{% url 'inventory:update' item.pk %}">{{ item.pk }}</a></td>
  <td>{{ item.make.name }}</td>
  <td>{% if item.net_price != 0 %}{{ item.net_price }} {% endif %}</td>
  <td>{{ item.price }}</td>
  <td>{{ item.quantity }}</td>
  <td>{{ item.unit.name }}</td>
  <td>
    <span style="color:grey;">
      {% if item.price_relation > 3 %}
      <strong><span style="color:red;">{{ item.price_relation }}</span></strong>
      {% elif item.price_relation < 1.5 %}
      <span style="color:blue;">{{ item.price_relation }}</span>
      {% else %}
      {{ item.price_relation }}
      {% endif %}
    </span>
  </td>
</tr>

{% endfor %}

{% endif %}

</table>

<form action="{% url 'inventory:create' %}" method="post">
  {% csrf_token %}

    {% for field in form %}
        {{ field }}
    {% endfor %}

  <input name="" type="submit" value="zapisz"/>
</form>

{% endblock %}

templates/inventory/inventory_confirm_delete.html
{% extends 'inventory/base_inventory.html' %}

{% block body %}

<h3>Potwierdzenie usunięcia pozycji</h3>

<form action="" method="post">
  {% csrf_token %}
  
  <p>Czy usunąć "<strong>{{ object }}</strong>"?</p>

  <input type="submit" value="Potwiedź" />
</form>

{% endblock %}

templates/inventory/inventory_form.html
{% extends 'inventory/base_inventory.html' %}

{% block body %}

<h5>dodaj nowy remanent</h5>

<form action="" method="post">
  {% csrf_token %}
  {{ form }}
  <div>
    <button>Dodaj</button>
  </div>
</form>

{% endblock %}

templates/inventory/inventory_select.html
{% extends 'inventory/base_inventory.html' %}

{% block title %}wybierz remanent{% endblock %}

{% block body %}

<h5>wybierz remanent</h5>

<p>jeśli nie ma, to utwórz nowy <a href="{% url 'inventory:inventory_create' %}">tutaj</a></p>

<form method='post' action="{% url 'inventory:inventory_select' %}">

  {% csrf_token %}

  {{ form.errors }}

  {{ form }}

    <label for="show_hidden">pokaż ukryte towary</label>
    <input type="checkbox" name="show_hidden" value="True" {% if request.session.show_hidden %}checked{% endif %} id="show_hidden" />

  <div><input type="submit" value="wybierz"/></div>
</form>

{% endblock %}

templates/inventory/inventory_update_form.html
{% extends 'inventory/base_inventory.html' %}
{% block body %}

<h3>Zmień dane remanentu</h2>
<form action="" method="post">
  {% csrf_token %}
  {{ form }}
  <button>Zmień</button>
</form>

{% endblock %}

templates/inventory/item_form.html
{% extends 'inventory/base_inventory.html' %}

{% block title %}dodawanie{% endblock %}

{% block body %}

<form method='post' action="{% url 'inventory:create' %}">

  {% csrf_token %}

  {{ form }}
  <p style="color:orange;">{{ form.errors }}</p>

  <div><input type="submit" value="dodaj"/></div>
</form>

{% endblock %}

templates/inventory/item_search.html
{% extends 'inventory/base_inventory.html' %}

{% load static %}

{% block title %}wyszukiwarka{% endblock %}

{% block body %}

<!-- search form -->

<form class="item_search" action="{% url 'inventory:item_search' %}" method="get">
  <ul>
    {{ form.as_ul }}
    <li>
      <input name="" type="submit" value="szukaj"/>
    </li>
  </ul>
</form>

<!-- item list -->

{% if object_list %}

<p>wynik: <strong>{{ item_num }}</strong></p>

<table class="items">
  <tr>
    <th>id</th>
    <th>nazwa</th>
    <th>{% if object_list.0.net_price != 0 %}c. netto{% endif %}</th>
    <th>cena</th>
    <th>ilość</th>
    <th>j.m.</th>
    <th>osoba</th>
    <th></th>
  </tr>
  
{% for item in object_list %}

<tr>
  <td><a class="item_id" href="{% url 'inventory:update' item.pk %}">{{ item.pk }}</a></td>
  <td>{{ item.make.name }}</td>
  <td>{% if item.net_price != 0 %}{{ item.net_price }} {% endif %}</td>
  <td>{{ item.price }}</td>
  <td>{{ item.quantity }}</td>
  <td>{{ item.unit.name }}</td>
  <td>{{ item.created_by.username }}</td>
  <td>
    <span style="color:grey;">
      {% if item.price_relation > 3 %}
      <strong><span style="color:red;">{{ item.price_relation }}</span></strong>
      {% else %}
      {{ item.price_relation }}
      {% endif %}
    </span>
</tr>

{% endfor %}

</table>

<!-- paginator -->

{% include 'inventory/paginator.html' %}

{% endif %}

{% endblock %}

templates/inventory/item_update_form.html
{% extends 'inventory/base_inventory.html' %}

{% block title %}edycja{% endblock %}

{% block body %}

<h3>edycja towaru</h3>

<p>jeśli chcesz wrócić bez zmian, naciśnij <a onClick="javascript:history.go(-1);">tutaj</a></p>

<form method='post' action="">

  {% csrf_token %}

  {{ form }}

  <div><input type="submit" value="zmień"/></div>
</form>

<p>Jeśli chcesz usunąć pozycję, naciśnij <a href="{% url 'inventory:delete' item.pk %}">tutaj</a></p>

{% endblock %}

templates/inventory/latex.html
{% extends 'inventory/base_inventory.html' %}
{% load static %}
{% block title %}latex{% endblock %}

{% block body %}

<form action="" method="post">

  {% csrf_token %}
  {{ form }}
  <input name="" type="submit" value="pdf"/>

</form>

{% endblock %}

templates/inventory/menu.html
{% load static %}

<div class="row" id="navbar">
  <div class="two columns">
    <h3>remanent</h3>
  </div>
  <div class="ten columns">
    <ul>
      {% if request.user.is_staff %}
      <li><a href="{% url 'inventory:stats' %}">stats</a></li>
      {% endif %}
      <li><a href="{% url 'inventory:inventory_select' %}">zmień sklep</a></li>
      <li><a href="{% url 'inventory:item_search' %}">szukaj</a></li>
      <li><a href="{% url 'inventory:shelf_reset' %}">zeruj licznik</a></li>
      <li><a href="{% url 'inventory:index' %}">pisz dalej</a></li>
    </ul>
  </div>
</div>

<div class="row" id="current_shop">
  <div class="eight columns">
    {% if current_inventory %}
    sklep: <strong>#{{ current_inventory }}</strong>
    {% endif %}
  </div>
  <div class="four columns" id="shelf_counter">
    {% if shelf_counter %}
    <a href="{% url 'inventory:item_search' %}" title="wyświetl półkę" class="">{{ shelf_counter.piece|add:shelf_counter.weight }}</a>
    {% endif %}
    {{ aqq }}
  </div>
</div>

templates/inventory/paginator.html
{% load templatehelpers %}

<div class="pagination">
  <span class="step-links">
    {% if page_obj.has_previous %}
    <a href="{% relative_url page_obj.previous_page_number 'page' request.GET.urlencode %}">&laquo; poprzednia</a>
    {% endif %}

    <span class="current">
      strona {{ page_obj.number }} z {{ page_obj.paginator.num_pages }}.
    </span>

    {% if page_obj.has_next %}
    <a href="{% relative_url page_obj.next_page_number 'page' request.GET.urlencode %}">następna &raquo;</a>
    {% endif %}
  </span>
</div>

templates/inventory/stats.html
{% extends 'inventory/base_inventory.html' %}

{% load static %}

{% block title %}podsumowanie{% endblock %}

{% block body %}

    <p>tryb remanentu: <h4>{{ current_inventory.price_mode }}</h4></p>

<p>suma netto:
  <h3>{{ sum.net|floatformat:2 }}</h3>
</p>
<p>suma brutto:
    <h3>{{ sum.gross|floatformat:2 }}</h3>
</p>
<p>ilość pozycji:
  <h4>{{ count }}</h4>
</p>

<p><a href="{% url 'inventory:latex' %}"><img alt="pdf" src="{% static 'icons/document.svg' %}"/> wydruk pdf</a></p>

{% if count_by_user %}
<table>
{% for item in count_by_user %}
<tr>
  <td>{{ item.created_by__username }}</td>
  <td>{{ item.count }} pozycji</td>
</tr>
{% endfor %}
</table>
{% endif %}

<table>
{% for group in sum_by_group %}
    <tr>
        <th>{{ group.make__group__name }}</th>
        <td>{{ group.sum }} zł</td>
    </tr>
{% endfor %}
</table>
{% endblock %}