gold/urls.py
from django.urls import path
from django.http import HttpResponse
#from django.contrib.auth.views import LoginView, LogoutView

from . import views


app_name = 'gold'

urlpatterns = [
    path('', views.contract_view, name='form'),
]

machines/urls.py
from django.urls import path
from . import views

app_name = 'machines'

urlpatterns = [
    path('', views.MachineIndex.as_view(), name='index'),
    path('<int:pk>/', views.MachineDetail.as_view(), name='detail'),
    path('add/', views.MachineCreate.as_view(), name='create'),
    path('<int:pk>/update/', views.MachineUpdate.as_view(), name='update'),
    path('<int:pk>/del/', views.MachineDelete.as_view(),
         name='delete'),
    path('upload/', views.MachineSetupUpload.as_view(),
         name='setup-upload'),
    path('service/', views.ServiceIndexView.as_view(), name='service_index'),
    path('service/add/', views.ServiceCreate.as_view(), name='service_create'),
    path('service/<int:pk>/del/', views.ServiceDelete.as_view(),
         name='service_delete'),
    path('service/<int:pk>/update/', views.ServiceUpdate.as_view(),
         name='service_update'),
    path('device/', views.DeviceIndexView.as_view(), name='device_index'),
    path('device/<int:pk>/', views.DeviceDetailView.as_view(),
         name='device_detail'),
    path('device/add/', views.DeviceCreate.as_view(), name='device_create'),
    path('device/<int:pk>/del/', views.DeviceDelete.as_view(),
         name='device_delete'),
    path('device/<int:pk>/update/', views.DeviceUpdate.as_view(),
         name='device_update'),
]

machines/models.py
from django.db import models
from django.urls import reverse

from datetime import date as datetime_date
import os
from uuid import uuid4


def device_upload_location(instance, filename):
    fname, ext = os.path.splitext(filename)
    name = instance.pk if instance.pk else uuid4().hex
    return "device/{name}{ext}".format(name=name, ext=ext)


class Machine(models.Model):
    name = models.CharField(max_length=50)
    FQDN = models.CharField(max_length=50, null=True, blank=True)
    date = models.DateField(null=True, blank=True)
    form = models.CharField(max_length=50, null=True, blank=True)
    bios = models.CharField(max_length=50, null=True, blank=True)
    prod = models.CharField(max_length=150, null=True, blank=True)
    vendor = models.CharField(max_length=150, null=True, blank=True)
    OS = models.CharField(max_length=150, null=True, blank=True)
    dist_major_ver = models.IntegerField(default=0, null=True, blank=True)
    kernel = models.CharField(max_length=150, null=True, blank=True)
    CPU = models.CharField(max_length=150, null=True, blank=True)
    cores = models.CharField(max_length=150, null=True, blank=True)
    arch = models.CharField(max_length=150, null=True, blank=True)
    mem = models.CharField(max_length=250, null=True, blank=True)
    HDD = models.CharField(max_length=250, null=True, blank=True)
    disk = models.CharField(max_length=250, null=True, blank=True)
    diskfree = models.CharField(max_length=250, null=True, blank=True)
    IPs = models.CharField(max_length=350, null=True, blank=True)
    gateway = models.CharField(max_length=250, null=True, blank=True)
    gate_iface = models.CharField(max_length=250, null=True, blank=True)
    location = models.ForeignKey('Location', null=True, blank=True,
                                 on_delete=models.SET_NULL)
    is_active = models.BooleanField(default=True, blank=True)

    class Meta:
        ordering = ['-is_active', 'FQDN']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('machines:detail', kwargs={'pk': self.pk})

    @property
    def mem_mb(self):
        try:
            int(self.mem)
        except (ValueError, TypeError):
            return ''
        else:
            return round(int(self.mem)/1000)

    @property
    def outdated_setup(self):
        if not self.date:
            return False
        dt = datetime_date.today() - self.date
        if dt.days > 90:
            return True
        else:
            return False

    @property
    def days_since(self):
        if self.date is not None:
            ds = (datetime_date.today() - self.date)
            return ds.days
        return ''


class Service(models.Model):
    machine = models.ForeignKey('Machine', on_delete=models.CASCADE)
    date = models.DateField()
    description = models.TextField(max_length=500)
    device = models.ForeignKey('Device',
                               blank=True,
                               null=True,
                               on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('machines:detail', kwargs={'pk': self.machine_id})

    def __str__(self):
        return self.description


class Device(models.Model):
    machine = models.ForeignKey('Machine',
                                blank=True,
                                null=True,
                                on_delete=models.SET_NULL,
                                related_name='device')
    date = models.DateField(null=True, blank=True)
    type = models.ForeignKey('DeviceType', on_delete=models.CASCADE)
    name = models.CharField(max_length=150, null=True)
    price = models.DecimalField(max_digits=5,
                                decimal_places=0,
                                blank=True,
                                null=True)
    company = models.CharField(max_length=150, blank=True, null=True)
    invoice = models.CharField(max_length=150, blank=True, null=True,
                               verbose_name='invoice number')
    location = models.ForeignKey('Location', null=True, blank=True,
                                 on_delete=models.SET_NULL)
    serial = models.CharField(max_length=150, blank=True, null=True,
                              verbose_name='serial number')
    invoice_pdf = models.FileField(upload_to=device_upload_location,
                                   blank=True, null=True)

    def get_absolute_url(self):
        return reverse('machines:device_detail', kwargs={'pk': self.pk})

    def __str__(self):
        string = "{} {}".format(str(self.date), self.name)
        return string

    class Meta:
        ordering = ['-pk']


class DeviceType(models.Model):
    name = models.CharField(unique=True, max_length=150, null=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class Location(models.Model):
    """ machine location list """

    name = models.CharField(max_length=50, null=True)
    address = models.CharField(max_length=150, null=True)

    def __str__(self):
        return self.address

machines/forms.py
from django import forms

from .models import DeviceType, Location, Service


class DeviceSearchForm(forms.Form):
    """ device search form """

    device_type = forms.ModelChoiceField(DeviceType.objects.all(),
                                         required=False)
    location = forms.ModelChoiceField(Location.objects.all(),
                                      required=False)


class MachineSetupForm(forms.Form):
    """ ansible setup form """

    file_field = forms.FileField(
        widget=forms.ClearableFileInput()
    )


class ServiceForm(forms.ModelForm):

    class Meta:
        model = Service
        fields = '__all__'
        widgets = {'description': forms.Textarea(attrs={'cols': 60,
                                                        'rows': 4}),
                   'machine': forms.Select(attrs={'autofocus': True})}

machines/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView, \
    FormMixin, FormView
from django.urls import reverse_lazy

from .models import Machine, Device, Service
from .forms import DeviceSearchForm, MachineSetupForm, ServiceForm

import time


class MachineIndex(LoginRequiredMixin, ListView):
    """
    host list
    """
    template_name = 'machines/index.html'
    context_object_name = 'machines'

    def get_queryset(self):
        return Machine.objects.prefetch_related('location')\
                              .order_by('-is_active', 'name')


class MachineDetail(DetailView):
    """
    host details
    """
    model = Machine
    template_name = 'machines/detail.html'
    queryset = Machine.objects.prefetch_related('device').all()


class MachineCreate(CreateView):
    """
    create a host
    """
    model = Machine
    fields = ['name', 'location']


class MachineUpdate(UpdateView):
    """
    edit machine
    """
    model = Machine
    fields = '__all__'


class MachineDelete(DeleteView):
    """
    remove a host
    """
    model = Machine
    success_url = reverse_lazy('machines:index')


class ServiceIndexView(LoginRequiredMixin, ListView):
    """
    service list
    """
    template_name = 'machines/service_index.html'
    context_object_name = 'services'
    paginate_by = 25

    def get_queryset(self):
        query = Service.objects.prefetch_related('machine', 'device')\
                .all()
        return query.order_by('-date')


class ServiceCreate(LoginRequiredMixin, CreateView):
    """
    service add
    """
    model = Service
    fields = ['machine', 'date', 'description', 'device']

    def get_initial(self, **kwargs):
        return {'machine': self.request.GET.get("machine_id", None),
                'date': time.strftime('%Y-%m-%d')}


class ServiceUpdate(LoginRequiredMixin, UpdateView):
    """
    service update
    """
    model = Service
    form_class = ServiceForm


class ServiceDelete(LoginRequiredMixin, DeleteView):
    """
    service delete
    """
    model = Service

    def get_success_url(self):
        machine = self.object.machine
        return reverse_lazy('machines:detail', kwargs={'pk': machine.pk})


class DeviceIndexView(LoginRequiredMixin, FormMixin, ListView):
    """
    component list
    """
    template_name = 'machines/device_index.html'
    form_class = DeviceSearchForm
    context_object_name = 'device'
    model = Device
    paginate_by = 25

    def get_queryset(self):
        query = Device.objects.prefetch_related('type', 'location').all()

        if self.device_type:
            query = query.filter(type=self.device_type)
        if self.location:
            query = query.filter(location=self.location)

        return query

    def get_initial(self):
        initials = {}

        if self.device_type:
            initials['device_type'] = self.device_type
        if self.location:
            initials['location'] = self.location

        return initials

    def dispatch(self, request, *args, **kwargs):

        self.device_type = request.GET.get('device_type', None)
        self.location = request.GET.get('location', None)
        return super().dispatch(request, *args, **kwargs)


class DeviceDetailView(LoginRequiredMixin, DetailView):
    """
    component detail
    """
    model = Device
    template_name = 'machines/device_detail.html'


class DeviceCreate(LoginRequiredMixin, CreateView):
    """
    component add
    """
    model = Device
    fields = ['type', 'location', 'date', 'name', 'price', 'company',
              'invoice', 'serial', 'machine', 'invoice_pdf']

    def get_initial(self, **kwargs):
        return {'date': time.strftime('%Y-%m-%d')}


class DeviceUpdate(LoginRequiredMixin, UpdateView):
    """
    component update
    """
    model = Device
    fields = ['type', 'location', 'date', 'name', 'price', 'company',
              'invoice', 'serial', 'machine', 'invoice_pdf']


class DeviceDelete(LoginRequiredMixin, DeleteView):
    """
    component delete
    """
    model = Device
    success_url = reverse_lazy('machines:device_index')


class MachineSetupUpload(FormView):
    """ upload ansile setup json """

    form_class = MachineSetupForm
    success_url = reverse_lazy('machines:index')
    template_name = 'machines/setup_upload.html'

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        files = request.FILES.getlist('file_field')

        if form.is_valid():
            for f in files:
                import json
                str = f.file.read().decode()
                j = json.loads(str)
                if 'failed' in j:
                    continue
                try:
                    fqdn = j['ansible_facts']['ansible_fqdn']
                except KeyError:
                    return self.form_invalid(form)

                try:
                    obj = Machine.objects.get(FQDN=fqdn)
                except Machine.DoesNotExist:
                    return self.form_invalid(form)

                try:
                    obj.date = j['ansible_facts']['ansible_date_time']['date']
                    obj.form = j['ansible_facts']['ansible_form_factor']
                    obj.bios = j['ansible_facts']['ansible_bios_date']
                    obj.prod = j['ansible_facts']['ansible_product_name']
                    obj.vendor = j['ansible_facts']['ansible_system_vendor']
                    obj.OS = "%s %s" % (j['ansible_facts']['ansible_distribution'],  # noqa
                                        j['ansible_facts']['ansible_distribution_version'])  # noqa
                    obj.kernel = j['ansible_facts']['ansible_kernel']
                    obj.CPU = j['ansible_facts']['ansible_processor'][2]
                    obj.cores = j['ansible_facts']['ansible_processor_cores']
                    obj.arch = j['ansible_facts']['ansible_architecture']
                    obj.mem = j['ansible_facts']['ansible_memtotal_mb']
                    # obj.disk = j ['ansible_facts']['ansible_devices']['sda']['model']  # noqa
                    obj.IPs = ', '.join(j['ansible_facts']['ansible_all_ipv4_addresses'])  # noqa
                    obj.gateway = j['ansible_facts']['ansible_default_ipv4']['gateway'],  # noqa
                    obj.gate_iface =j['ansible_facts']['ansible_default_ipv4']['interface']  # noqa
                except KeyError:
                    pass

                obj.save()

            return self.form_valid(form)
        else:
            return self.form_invalid(form)

templates/machines/base_machines.html
{% extends 'base.html' %}

{% block title %}machines{% endblock %}

{% block navbar %}

<div class="row" id="navbar">
  <div class="two columns">
    <h3>Machines</h3>
  </div>
  <div class="ten columns">
    <ul>
      <li><a href="{% url 'machines:service_index' %}">service</a></li>
      <li><a href="{% url 'machines:device_index' %}">devices</a></li>
      <li><a href="{% url 'machines:index' %}">machines</a></li>
    </ul>
  </div>
</div>

{% endblock %}

templates/machines/detail.html
{% extends 'machines/base_machines.html' %}
{% block body %}

<div class="navbar3">
  <div class="navbar3-header"> Machine: {{ machine.name }}</div>
  <div class="u-pull-right">
    <a class="button button-primary" href="{% url 'machines:update' machine.pk %}">edit</a>
  </div>
</div>

<table>
  <tr>
      <th>Name</th><td>{{ machine.name }}</td>
      <th>FQDN</th><td>{{ machine.FQDN }}</td>
      <th>Active</th><td>
          {% if machine.is_active %}
              <span style="color:darkgreen;">True</span>
          {% else %}
              <span style="color:red;">False</span>
          {% endif %}
      </td>
  </tr>
  <tr>
    <th>Date</th><td>{{ machine.date }}</td>
    <th>Form</th><td>{{ machine.form }}</td>
  </tr>
  <tr>
    <th>Bios</th><td>{{ machine.bios }}</td>
    <th>Prod</th><td>{{ machine.prod }}</td>
  </tr>
  <tr>
    <th>Vendor</th><td>{{ machine.vendor }}</td>
    <th>OS</th><td>{{ machine.OS }}</td>
  </tr>
  <tr>
    <th>Kernel</th><td>{{ machine.kernel }}</td>
    <th>CPU</th><td>{{ machine.CPU }}</td>
  </tr>
  <tr>
    <th>Cores</th><td>{{ machine.cores }}</td>
    <th>Arch</th><td>{{ machine.arch }}</td>
  </tr>
  <tr>
    <th>Mem</th><td>{{ machine.mem }}</td>
    <th>HDD</th><td>{{ machine.HDD }}</td>
  </tr>
  <tr>
    <th>Disk</th><td>{{ machine.disk }}</td>
    <th>Diskfree</th><td>{{ machine.diskfree }}</td>
  </tr>
  <tr>
    <th>IPs</th><td>{{ machine.IPs }}</td>
    <th>Gateway</th><td>{{ machine.gateway }}</td>
  </tr>
  <tr>
    <th>Gate Iface</th><td>{{ machine.gate_iface }}</td>
    <th>Location</th><td>{{ machine.location.address }}</td>
  </tr>
</table>

{% if machine.device %}

<div class="navbar3">
  <div class="navbar3-header">Devices</div>
  <div class="u-pull-right">
    <a class="button button-primary" href="">add</a>
  </div>
</div>

<table class="table table-striped">
  <tr>
    <th>id</th>
    <th>date </th>
    <th>type </th>
    <th>name</th>
    <th>price</th>
    <th>company</th>
  </tr>
  {% for device in machine.device.all %}
  <tr>
    <td><a href="{% url 'machines:device_detail' device.pk %}">{{ device.pk }}</a></td>
    <td>{{ device.date }}</td>
    <td>{{ device.type }}</td>
    <td>{{ device.name }}</td>
    <td>{{ device.price }}</td>
    <td>{{ device.company }}</td>
  </tr>
  {% endfor %}
</table>

{% endif %}

<div class="navbar3">
  <div class="navbar3-header">Maintenance</div>
  <div class="u-pull-right">
    <a class="button button-primary" href="{% url 'machines:service_create' %}?machine_id={{ machine.pk }}">add</a>
  </div>
</div>

<table class="table">
  <tr>
    <th>id</th>
    <th>date</th>
    <th>description</th>
    <th></th>
  </tr>
{% for service in machine.service_set.all %}
  <tr>
    <td>{{ service.pk }}</td>
    <td>{{ service.date }}</td>
    <td>{{ service.description }}
      {% if service.device %}
      [{{ service.device.name }} <a href="{% url 'machines:device_detail' service.device.pk %}">detail</a>]
      {% endif %}
    </td>
    <td>
      <a class="button button-primary" href="{% url 'machines:service_update' service.pk %}">edit</a>
      <a class="button" href="{% url 'machines:service_delete' service.pk %}">delete</a>
    </td>
  </tr>
{% endfor %}
</table>

<a class="button red" href="{% url 'machines:delete' machine.pk %}">delete this machine</a>


{% endblock %}

templates/machines/device_confirm_delete.html
{% extends 'machines/base_machines.html' %}
{% block body %}

<div class="row">
  <div class="four columns">
      <form action="" method="post">{% csrf_token %}
        <p>Delete "{{ object }}"?</p>
        <input type="submit" value="confirm" />
      </form>
  </div>
</div>

{% endblock %}

templates/machines/device_detail.html
{% extends 'machines/base_machines.html' %}
{% block body %}

<h2></h2>


<div class="navbar3">
  <div class="navbar3-header">{{ device.type|capfirst }} > {{ device.name }}</div>
  <div class="u-pull-right">
    <a class="button button-primary" href="{% url 'machines:device_update' device.pk %}">edit</a>
    <a class="button" href="{% url 'machines:device_delete' device.pk %}">delete</a>
  </div>
</div>

<table>
  <tr>
    <th>location</th>
    <td>{{ device.location.address }}</td>
  </tr>
  <tr>
    <th>date</th>
    <td>{{ device.date }}</td>
  </tr>
  <tr>
    <th>type</th>
    <td>{{ device.type }}</td>
  </tr>
  <tr>
    <th>name</th>
    <td>{{ device.name }}</td>
  </tr>
  <tr>
    <th>price</th>
    <td>{{ device.price }} zł</td>
  </tr>
  <tr>
    <th>company</th>
    <td>{{ device.company }}</td>
  </tr>
  <tr>
    <th>invoice</th>
    <td>{{ device.invoice }}</td>
  </tr>
  <tr>
    <th>serial number</th>
    <td>{{ device.serial|default_if_none:'' }}</td>
  </tr>
  {% if device.invoice_pdf %} 
  <tr>
    <th>invoice preview</th>
    <td> <a target="_blank" href="{{ device.invoice_pdf.url }}"/>invoice</a></td>
  </tr>
{% endif %}
</table>


{% endblock %}

templates/machines/device_form.html
{% extends 'machines/base_machines.html' %}
{% block body %}

<div class="row">
  <div class="twelve columns">
    <div class="navbar3">
      <div class="navbar3-header">Device</div>
    </div>
  </div>
</div>
<form action="" method="post" enctype="multipart/form-data">
  <div class="row">
    <div class="six columns">
      
      {% csrf_token %}
      
      {# Include the hidden fields #}
      {% for hidden in form.hidden_fields %}
      {{ hidden }}
      {% endfor %}
      {# Include the visible fields #}
      {% for field in form.visible_fields %}
      
      {% if forloop.counter == 6 %}

    </div>
    <div class="six columns">
    
      {% endif %}
      
      <div class="fieldWrapper">
        {{ field.errors }}
        {{ field.label_tag }} {{ field }}
      </div>
      
      {% endfor %}
    
    </div>
  </div>
  <hr>
  <input name="" type="submit" class="button button-primary" value="save"/>
</form>

{% endblock %}

templates/machines/device_index.html
{% extends 'machines/base_machines.html' %}

{% load static %}

{% block body %}

    <div class="navbar3">
        <div class="navbar3-header">Device index</div>
        <div class="u-pull-right">
            <a class="button button-primary" href="{% url 'machines:device_create' %}">add</a>
        </div>
    </div>

    <div class="row">
        <div class="twelve columns" id="device-search">
            <form action="{% url 'machines:device_index' %}" method="get">

                <ul>
                    {% csrf_token %}
                    {{ form.as_ul }}

                    <li><label for="">&nbsp;</label><input name="" type="submit" value="search" /></li>
                </ul>
            </form>
        </div>
    </div>

    {% if device %}

        <div class="row">
            <div class="twelve columns">
                <table>
                    <tr>
                        <th>id</th>
                        <th>type</th>
                        <th>name</th>
                        <th>location</th>
                        <th>date</th>
                        <th>invoice</th>
                        {% for item in device %}
                            <tr>
                                <td><a href="{% url 'machines:device_detail' item.pk %}">{{ item.pk }}</a></td>
                                <td class="nowrap">{{ item.type }}</td>
                                <td>{{ item.name }}</td>
                                <td>{{ item.location.name }}</td>
                                <td class="nowrap">{{ item.date }}</td>
                                <td>
                                    {% if item.invoice_pdf %}
                                        <a href="{% get_media_prefix %}/{{ item.invoice_pdf }}"><img alt="pdf" src="{% static 'icons/document.svg' %}"/></a>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                </table>
            </div>
        </div>
    {% endif %}

    {% include "machines/paginator.html" %}

{% endblock %}

templates/machines/index.html
{% extends 'machines/base_machines.html' %}
{% block body %}

<div class="navbar3">
  <div class="navbar3-header">Machine index</div>
  <div class="u-pull-right">
    <a class="button button-primary" href="{% url 'machines:setup-upload' %}">upload setup</a>
    <a class="button button-primary" href="{% url 'machines:create' %}">add</a>
  </div>
</div>

{% if machines %}
<table>
  <tr>
    <th>ID</th>
    <th>Name / FQDN</th>
    <th>Form / BIOS</th>
    <th>Prod / Vendor</th>
    <th>Kernel / System</th>
    <th>Location / Update</th>
  </tr>
  {% for machine in machines %}
      <tr
          {% if not machine.is_active %}
              class="inactive"
          {% endif %}
      >
    <td><a href="{% url 'machines:detail' machine.pk %}">{{ machine.pk }}</a></td>
    <td class="nowrap">{{ machine.name }}<br/>
      <span class="grey">{{ machine.FQDN }}</span></td>
    <td>{{ machine.form }}<br/>
      <span class="grey">{{ machine.bios }}</span></td>
    <td>{{ machine.prod }}<br/>
      <span class="grey">{{ machine.vendor }}</span></td>
    <td>{{ machine.kernel }} <br/>
      <span class="grey">{{ machine.OS }}</span></td>
    <td class="nowrap">{{ machine.location.name }}<br/>
      <span class="grey">{{ machine.days_since }} days ago</span>
      {% if machine.outdated_setup %}<span class="warning_sign">&#9889;</span>{% endif %}</td>
  </tr>
  {% endfor %}
</table>
{% endif %}
{% endblock %}

templates/machines/machine_confirm_delete.html
{% extends 'machines/base_machines.html' %}
{% block body %}

<div class="row">
  <div class="four columns">
      <form action="" method="post">{% csrf_token %}
        <p>Delete "{{ object }}"?</p>
        <input type="submit" value="confirm" />
      </form>
  </div>
</div>

{% endblock %}

templates/machines/machine_form.html
{% extends 'machines/base_machines.html' %}
{% block body %}

<div class="row">
  <div class="four columns">
    <div class="navbar3">
      <div class="navbar3-header">Edit machine</div>
    </div>
    <form action="" method="post">
      {{ form }}
      {% csrf_token %}
      <button style="display:block;">submit</button>
    </form>
  </div>
</div>

{% endblock %}

templates/machines/paginator.html
{% if is_paginated %}
<!-- Paginator -->
<div class="row text-center">
  <nav aria-label="Page navigation">
    {% if page_obj.has_other_pages %}
    <ul class="pagination">
      {% if page_obj.has_previous %}
      <li><a aria-label="Previous" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
      </li>
      {% else %}
      <li class="disabled"><span>&laquo;</span></li>
      {% endif %}
      {% for pages in page_obj.paginator.page_range %}
      {% if page_obj.number == pages %}
      <li class="active"><span>{{pages}}
	  <span class="sr-only">(current)</span></span></li>
      {% else %}
      <li><a href="?page={{pages}}">{{pages}}</a></li>
      {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
      <li><a href="?page={{page_obj.next_page_number}}">&raquo;</a></li>
      {% else %}
      <li class="disabled"><span>&raquo;</span></li>
      {% endif %}
    </ul>
    {% endif %}
  </nav>
</div>
<!-- end Paginator -->
{% endif %}

templates/machines/service_confirm_delete.html
{% extends 'machines/base_machines.html' %}
{% block body %}

<div class="row">
  <div class="four columns">
      <form action="" method="post">{% csrf_token %}
        <p>Delete "{{ object }}"?</p>
        <input name="machine_id" type="hidden" value="{{ object.machine.pk }}"/>
        <input type="submit" value="confirm" />
      </form>
  </div>
</div>

{% endblock %}

templates/machines/service_form.html
{% extends 'machines/base_machines.html' %}
{% block body %}

<div class="row">
  <div class="twelve columns">
    <div class="navbar3">
      <div class="navbar3-header">Service</div>
    </div>

    <form action="" method="post">
      {{ form }}
      {% csrf_token %}
      <div>
        <hr>
        <input class="button button-primary" name="" type="submit" value="submit"/>
      </div>
    </form>
  </div>
</div>

{% endblock %}

templates/machines/service_index.html
{% extends 'machines/base_machines.html' %}
{% block body %}

<div class="navbar3">
  <div class="navbar3-header">Service activity list</div>
  <div class="u-pull-right">
  
  </div>
</div>

{% if services %}

<table class="table table-striped">
  {% for service in services %}
  <tr>
    <td>{{ service.pk }}</td>
    <td><a href="{% url 'machines:detail' service.machine.pk %}">{{ service.machine }}</a></td>
    <td class="nowrap">{{ service.date }}</td>
    <td>{{ service.description }}
      {% if service.device %}
      [{{ service.device.name }}]
      {% endif %}
    </td>
    <td class="nowrap">
      <a class="button button-primary" href="{% url 'machines:service_update' service.pk %}">edit</a>
      <a class="button" href="{% url 'machines:service_delete' service.pk %}">delete</a>
    </td>
  </tr>
  {% endfor %}
</table>

{% include "machines/paginator.html" %}

{% endif %}

{% endblock %}

templates/machines/setup_upload.html
{% extends 'machines/base_machines.html' %}
{% block body %}

<div class="row">
  <div class="twelve columns">
    <div class="navbar3">
      <div class="navbar3-header">setup upload</div>
    </div>
    <form action="" method="post" enctype="multipart/form-data">
      <p>Upload json file with ansible setup.</p>
      {{ form }}
      {% csrf_token %}
      <div><input name="" type="submit" value="submit"/></div>
    </form>
  </div>
</div>

{% endblock %}