gold/urls.py
from django.urls import path
from django.http import HttpResponse
#from django.contrib.auth.views import LoginView, LogoutView

from . import views


app_name = 'gold'

urlpatterns = [
    path('', views.contract_view, name='form'),
]

invoices/urls.py
from django.urls import path

from . import views

app_name = 'invoices'

urlpatterns = [
    # Invoices
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.InvoiceDetailView.as_view(), name='detail'),
    path('<int:customer>/add/', views.InvoiceCreateView.as_view(),
         name='create'),
    path('<int:pk>/update/', views.InvoiceUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.InvoiceDeleteView.as_view(), name='delete'),
    # Invoice Item
    path('item/<int:invoice>/add/', views.InvoiceItemCreateView.as_view(),
         name='invoice-item-create'),
    path('item/<int:pk>/update/', views.InvoiceItemUpdateView.as_view(),
         name='invoice-item-update'),
    path('item/<int:pk>/delete/', views.InvoiceItemDeleteView.as_view(),
         name='invoice-item-delete'),
    # Customers
    path('customer/', views.CustomerIndexView.as_view(),
         name='customer-index'),
    path('customer/<int:pk>/', views.CustomerDetailView.as_view(),
         name='customer-detail'),
    path('customer/add/', views.CustomerCreateView.as_view(),
         name='customer-create'),
    path('customer/<int:pk>/update/', views.CustomerUpdateView.as_view(),
         name='customer-update'),
    path('customer/<int:pk>/delete/', views.CustomerDeleteView.as_view(),
         name='customer-delete'),
    # Generate an invoice
    path('latex/<int:invoice>/', views.latex, name='latex'),
    # path('', views.as_view(), name=''),
]

invoices/models.py
from django.db import models
from django.urls import reverse
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from common.validators import validate_tax_id
from common.models import TimeStampedModel
from inventory.models import Make


class Invoice(TimeStampedModel):
    """ invoices """

    PAYMENTS = (
        ('1', 'gotówka'),
        ('2', 'karta'),
        ('3', 'przelew')
    )

    PLACES = (
        ('1', 'Ustroń'),
        ('2', 'Wisła'),
        ('3', 'Cieszyn')
    )
    
    number = models.CharField(max_length=35, verbose_name="numer faktury")
    customer = models.ForeignKey('Customer',
                                 verbose_name="klient",
                                 on_delete=models.CASCADE)
    issued = models.DateField(verbose_name="data wystawienia")
    transaction = models.DateField(verbose_name="data sprzedaży")
    due = models.DateField(verbose_name="termin płatności")
    payment = models.CharField(max_length=1, default='1', choices=PAYMENTS,
                               verbose_name="sposób płatności")
    issue_place = models.CharField(max_length=1, default='1', choices=PLACES,
                                   verbose_name="miejsce wydania faktury")
    
    def __str__(self):
        string = "{}, {}, {}".format(
            self.number, self.issued, self.customer)
        return string

    def get_absolute_url(self):
        return reverse('invoices:detail',
                       kwargs={'pk': self.id})


class InvoiceItem(models.Model):
    """ items on invoice """

    invoice = models.ForeignKey('Invoice', on_delete=models.CASCADE)
    make = models.ForeignKey(Make, verbose_name="towar",
                             on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=7, decimal_places=2,
                                verbose_name="cena brutto")
    vat = models.FloatField(default=23)
    qty = models.FloatField(default=1, verbose_name="ilość")

    @property
    def net_price(self):
        """ calculate net price """
        
        return float(self.price)/(1+(self.vat/100))

    @property
    def net_total(self):
        """ multiply net price and qty """

        return self.net_price * self.qty

    @property
    def tax(self):
        """ calculate tax """

        return (float(self.price)-self.net_price) * self.qty

    @property
    def total_price(self):
        """ multiply price and qty """

        return float(self.price) * self.qty
        
    def __str__(self):
        string = "{}, {}, {}, {}".format(
            self.make, self.qty, self.price, self.vat)
        return string

    def get_absolute_url(self):
        return reverse('invoices:detail',
                       kwargs={'pk': self.invoice.pk})


class Customer(TimeStampedModel):
    """ counterparties """

    company = models.CharField(max_length=35,
                               null=True,
                               blank=True,
                               verbose_name="nazwa firmy")
    name = models.CharField(max_length=35,
                            null=True,
                            blank=True,
                            verbose_name="imię i nazwisko")
    street = models.CharField(max_length=35,
                              null=True,
                              blank=True,
                              verbose_name="ulica")
    city = models.CharField(max_length=35,
                            blank=True,
                            null=True,
                            verbose_name="miasto")
    tax_id = models.CharField(max_length=35,
                              blank=True,
                              null=True,
                              unique=True,
                              verbose_name="NIP",
                              help_text="tylko cyfry")
    email = models.EmailField(max_length=50,
                              blank=True,
                              null=True)
    phone = models.CharField(max_length=35,
                             blank=True,
                             null=True,
                             verbose_name="telefon")
    postal_code = models.CharField(max_length=6,
                                   blank=True,
                                   null=True,
                                   verbose_name="kod pocztowy")

    class Meta:
        verbose_name = "klient"
        verbose_name_plural = "klienci"

    def __str__(self):
        string = "{}, {}, {}, {}, {}".format(
            self.company,
            self.name,
            self.street,
            self.city,
            self.tax_id)
        return string

    def get_absolute_url(self):
        return reverse('invoices:customer-detail',
                       kwargs={'pk': self.id})

    def clean(self):
        if self.tax_id is not None and\
           self.tax_id.isdigit() and\
           not validate_tax_id(self.tax_id):
            raise ValidationError({'tax_id':
                                   _('Nieprawidłowa suma kontrolna NIP')})

        if self.company is None and self.name is None:
            raise ValidationError({'company':
                                   _('Musisz wpisać nazwę firmy albo nazwisko')
                                   })

invoices/forms.py
from django import forms

from datetime import date

from .models import Invoice, InvoiceItem, Customer
from inventory.models import Make


class InvoiceForm(forms.ModelForm):

    transaction = forms.DateField(initial=date.today(),
                                  label="Data sprzedaży",
                                  widget=forms.DateInput(format='%Y-%m-%d'),
                                  input_formats=['%Y-%m-%d'])

    issued = forms.DateField(initial=date.today(),
                             label="Data wystawienia",
                             widget=forms.DateInput(format='%Y-%m-%d'),
                             input_formats=['%Y-%m-%d'])

    due = forms.DateField(initial=date.today(),
                          label="Termin płatności",
                          widget=forms.DateInput(format='%Y-%m-%d'),
                          input_formats=['%Y-%m-%d'])

    field_order = ['customer', 'number', 'issue_place', 'payment',
                   'issued', 'transaction', 'due']

    class Meta:
        model = Invoice
        fields = ['number', 'issued', 'customer', 'transaction', 'issue_place',
                  'due', 'payment']

        widgets = {'customer': forms.HiddenInput(),
                   'number': forms.TextInput(attrs={
                       'autofocus': True})}
        
        
class InvoiceItemForm(forms.ModelForm):

    make = forms.ModelChoiceField(Make.objects.all().order_by('name'),
                                  label="Nazwa towaru")

    field_order = ['make', 'price', 'qty', 'vat']
    
    class Meta:
        model = InvoiceItem
        fields = '__all__'
        widgets = {'invoice': forms.HiddenInput(),
                   'vat': forms.TextInput(attrs={'size': 3}),
                   'price': forms.TextInput(attrs={'size': 5}),
                   'qty': forms.TextInput(attrs={'size': 3})}


class CustomerSearchForm(forms.Form):

    name = forms.CharField(label="nazwa",
                           widget=forms.TextInput(attrs={'autofocus': True}))
        

class CustomerForm(forms.ModelForm):

    def __init__(self, *args, session_data=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['company'].widget = forms.TextInput(
            attrs={"autofocus": True})

    field_order = ['company',
                   'name',
                   'street',
                   'postal_code',
                   'city',
                   'tax_id',
                   'email',
                   'phone']
    
    class Meta:
        model = Customer
        fields = '__all__'
        exclude = ['created_by']

invoices/views.py
# from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView,\
    FormMixin
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.conf import settings

from djatex import render_latex
from num2words import num2words

from .models import Invoice, InvoiceItem, Customer
from .forms import InvoiceForm, InvoiceItemForm, CustomerSearchForm,\
    CustomerForm
from .utils import SumItems
from common.mixins import CreatedByMixin


class IndexView(LoginRequiredMixin, ListView):
    """List of invoices"""

    model = Invoice
    template_name = 'invoices/index.html'
    
    def get_queryset(self):
        queryset = Invoice.objects.filter(created_by=self.request.user)
        return queryset


class InvoiceDetailView(LoginRequiredMixin, FormMixin, DetailView):
    """Invoice detail"""

    model = Invoice
    template_name = 'invoices/detail.html'
    form_class = InvoiceItemForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        invoice = self.kwargs['pk']
        items = InvoiceItem.objects.filter(invoice=invoice)

        context['items'] = items
        context['total'] = SumItems(invoice)
        
        return context

    def get_initial(self):
        return {'invoice': self.kwargs['pk']}


class InvoiceCreateView(LoginRequiredMixin, CreatedByMixin, CreateView):
    """Create an invoice"""

    model = Invoice
    template_name = 'invoices/create.html'
    form_class = InvoiceForm

    def get_initial(self):
        return {'customer': self.kwargs['customer']}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['customer'] = Customer.objects.get(pk=self.kwargs['customer'])
        return context
    

class InvoiceUpdateView(LoginRequiredMixin, CreatedByMixin, UpdateView):
    """Update an invoice"""

    model = Invoice
    template_name = 'invoices/create.html'
    form_class = InvoiceForm
    

class InvoiceDeleteView(LoginRequiredMixin, DeleteView):
    """Delete an invoice"""

    model = Invoice
    template_name = 'invoices/_confirm_delete.html'
    
    def get_success_url(self):
        customer = self.object.customer
        return reverse_lazy('invoices:customer-detail',
                            kwargs={'pk': customer.pk})


class InvoiceItemCreateView(LoginRequiredMixin, CreateView):
    """Create an invoice item"""

    model = InvoiceItem
    template_name = 'invoices/invoice_item_create.html'
    form_class = InvoiceItemForm
    
    def get_initial(self):
        return {'invoice': self.kwargs['invoice']}


class InvoiceItemUpdateView(LoginRequiredMixin, UpdateView):
    """Update an invoice item"""

    model = InvoiceItem
    template_name = 'invoices/invoice_item_create.html'
    form_class = InvoiceItemForm


class InvoiceItemDeleteView(LoginRequiredMixin, DeleteView):
    """Delete an invoice item"""

    model = InvoiceItem
    template_name = 'invoices/_confirm_delete.html'

    def get_success_url(self):
        invoice = self.object.invoice
        return reverse_lazy('invoices:detail', kwargs={'pk': invoice.pk})


class CustomerIndexView(LoginRequiredMixin, FormMixin, ListView):
    """List of customers"""

    model = Customer
    template_name = 'invoices/customer_index.html'
    ordering = ['company', 'name']
    form_class = CustomerSearchForm

    def get_queryset(self):
        customers = Customer.objects.all()

        name = self.request.GET.get('name', None)

        if name and name != '':
            customers = customers.filter(
                Q(name__icontains=name) |
                Q(company__icontains=name)
            )
        
        return customers
    

class CustomerDetailView(LoginRequiredMixin, DetailView):
    """Customer details"""
    
    model = Customer
    template_name = 'invoices/customer_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['invoices'] = Invoice.objects.filter(
            customer=self.kwargs['pk'],
            created_by=self.request.user
        )
        
        return context

    
class CustomerCreateView(LoginRequiredMixin, CreatedByMixin, CreateView):
    """Create a customer"""

    model = Customer
    template_name = 'invoices/customer_create.html'
    form_class = CustomerForm
    

class CustomerUpdateView(LoginRequiredMixin, UpdateView):
    """Update a customer"""

    model = Customer
    template_name = 'invoices/customer_update.html'
    fields = ['company', 'name', 'street', 'city',
              'postal_code', 'tax_id', 'email', 'phone']


class CustomerDeleteView(LoginRequiredMixin, DeleteView):
    """Delete a customer"""

    model = Customer
    template_name = 'invoices/_confirm_delete.html'

    def get_success_url(self):
        return reverse_lazy('invoices:customer-index')


@login_required
def latex(request, **kwargs):
    """Generate an invoice in PDF"""
    
    invoice = kwargs['invoice']

    invoice_data = Invoice.objects.get(pk=invoice)
    items = InvoiceItem.objects.filter(invoice=invoice)

    if invoice_data.created_by_id in [1,14]:
        account = "40 1050 1096 1000 0090 7197 0892"
    else:
        account = "94 1050 1096 1000 0001 0109 3797"
    
    file_name = "faktura_{id}_z_{date}.pdf".format(
        id=invoice, date=invoice_data.issued)

    total, vats = SumItems(invoice)

    context = {'invoice': invoice_data,
               'account': account,
               'items': items,
               'vats': vats,
               'total': total,
               'total_words': num2words(total['sum'], lang='pl')}
    
    return render_latex(request, file_name, 'invoices/invoice.tex',
                        error_template_name='invoices/error.html',
                        home_dir=settings.TEX_HOME,
                        context=context)

templates/invoices/_confirm_delete.html
{% extends 'invoices/base_invoices.html' %}
{% load static %}
{% block title %}faktury{% endblock %}

{% block body %}

<h3>Potwierdzenie usunięcia pozycji</h3>

<form action="" method="post">
  {% csrf_token %}
  
  <p>Czy usunąć "<strong>{{ object }}</strong>"?</p>

  <input type="submit" value="Potwiedź" />
</form>

{% endblock %}

templates/invoices/base_invoices.html
{% extends 'base.html' %}
{% load static %}

{% block navbar %}

<div class="row" id="navbar">
  <div class="twelve columns">
    <h3>Faktury</h3>
  </div>
</div>
<div class="row">
  <div class="eight columns left" id="navbar-main">
    <ul>
      <li><a href="{% url 'invoices:customer-index' %}">Klienci</a></li>
      <li><a href="{% url 'invoices:index' %}">Historia faktur</a></li>
    </ul>
  </div>
  <div class="four columns right" id="navbar-main">
  </div>
</div>

{% endblock navbar %}

templates/invoices/create.html
{% extends 'invoices/base_invoices.html' %}
{% load static %}
{% block title %}faktury{% endblock %}

{% block body %}

{% if customer %}
<h5>Faktura dla: {{ customer.company|default_if_none:customer.name }}</h5>
{% endif %}

<div class="row">
  <div class="four columns">
    <form action="" method="post">

      {% csrf_token %}

      {# Include the hidden fields #}
      {% for hidden in form.hidden_fields %}
      {{ hidden }}
      {% endfor %}
      {# Include the visible fields #}
      {% for field in form.visible_fields %}
      
      {% if forloop.counter == 4 %}

  </div>
  <div class="six columns">
      
      {% endif %}

      <div class="fieldWrapper">
        {{ field.errors }}
        {{ field.label_tag }} {{ field }}
      </div>
      {% endfor %}

      <div>&nbsp;</div>
      <div>
        <input class="button-primary" name="" type="submit" value="dalej"/>
      </div>
      
    </form>
    </div>
</div>

{% endblock %}

templates/invoices/customer_create.html
{% extends 'invoices/base_invoices.html' %}
{% load static %}
{% block title %}faktury{% endblock %}

{% block body %}

<h4>Nowy klient</h4>

<div class="row">
  <div class="four columns">
    <form action="" method="post">

      {% csrf_token %}

      {# Include the hidden fields #}
      {% for hidden in form.hidden_fields %}
      {{ hidden }}
      {% endfor %}
      {# Include the visible fields #}
      {% for field in form.visible_fields %}
      
      {% if forloop.counter == 5 %}

  </div>
  <div class="six columns">
      
      {% endif %}

      <div class="fieldWrapper">
        {{ field.errors }}
        {{ field.label_tag }} {{ field }}
      </div>
      {% endfor %}

      <div>&nbsp;</div>
      <div>
        <input class="button-primary" name="" type="submit" value="zapisz"/>
      </div>
      
    </form>
    </div>
</div>

{% endblock %}

templates/invoices/customer_detail.html
{% extends 'invoices/base_invoices.html' %}
{% load static %}
{% block title %}faktury{% endblock %}

{% block body %}

{% if object %}

<h4>Klient: {{ object.company|default_if_none:object.name }}</h4>

<a class="button" href="{% url 'invoices:customer-update' object.pk %}">zmień dane</a>
<a class="button button-primary" href="{% url 'invoices:create' object.pk %}">wystaw nową fakturę</a>

<table>
  <tr>
    <th>miasto</th>
    <td>{{ object.city|default_if_none:"-" }}</td>
    <th>ulica</th>
    <td>{{ object.street|default_if_none:"-" }}</td>
  </tr>
  <tr>
    <th>email</th>
    <td>{{ object.email|default_if_none:"-" }}</td>
    <th>NIP</th>
    <td>{{ object.tax_id|default_if_none:"-" }}</td>
  </tr>
  <tr>
    <th>telefon</th>
    <td>{{ object.phone|default_if_none:"-" }}</td>
    <th></th>
    <td></td>
  </tr>
</table>

{% endif %} {# object #}

<div>&nbsp;</div>

{% if invoices %}

<h5>Wystawione faktury</h5>

<table>

{% for invoice in invoices %}

<tr>
  <td>{{ invoice.number|default_if_none:"-" }}</td>
  <td>{{ invoice.issued|default_if_none:"-" }}</td>
  <td><a href="{% url 'invoices:detail' invoice.pk %}">szczegóły</a></td>
</tr>


{% endfor %}

</table>

{% endif %} {# invoices #}

<a class="" href="{% url 'invoices:customer-delete' object.pk %}">usuń klienta</a>

{% endblock %}

templates/invoices/customer_index.html
{% extends 'invoices/base_invoices.html' %}
{% load static %}
{% block title %}faktury{% endblock %}

{% block body %}

<div class="row">
  <div class="twelve columns">
    <a class="button button-primary" href="{% url 'invoices:customer-create' %}">dodaj klienta</a>

    <form action="" method="get">
      <div class="inline">
        <ul>
          {% csrf_token %}
          {{ form.as_ul }}
          <li>
            <label for="">&nbsp;</label>
            <input name="" type="submit" value="szukaj"/>
          </li>
        </ul>
      </div>
    </form>
  </div>
</div>

{% if object_list %}

<div class="row">
  <div class="twelve columns">
    <table>

      <tr>
        <th>firma</th>
        <th>adres</th>
        <th>telefon</th>
        <th>email</th>
        <th></th>
      </tr>
  
      {% for item in object_list %}

      <tr>
        <td>{{ item.company|default_if_none:"" }} {{ item.name|default_if_none:"" }}</td>
        <td>
          {% if item.street %} ul. {{ item.street }}, {% endif %} {{ item.city|default_if_none:"" }}</td>
        <td>{{ item.phone|default_if_none:"-" }}</td>
        <td>{{ item.email|default_if_none:"-" }}</td>
        <td><a href="{% url 'invoices:customer-detail' item.pk %}">wybierz</a></td>
      </tr>

      {% endfor %}

    </table>
  </div>
</div>
{% endif %} {# object_list #}

{% endblock %}

templates/invoices/customer_update.html
{% extends 'invoices/base_invoices.html' %}
{% load static %}
{% block title %}faktury{% endblock %}

{% block body %}

<form action="" method="post">

  {% csrf_token %}
  {{ form }}

  <div>
    <input name="" type="submit" value="zmień"/>
  </div>
  
</form>

{% endblock %}

templates/invoices/detail.html
{% extends 'invoices/base_invoices.html' %}
{% load static %}
{% block title %}faktura{% endblock %}

{% block body %}

{% if object %}

<h4><span>Faktura</span> {{ object.number }} dla {{ object.customer.company|default_if_none:object.customer.name }}</h4>

<div>
  <a class="button" href="{% url 'invoices:update' object.pk %}">edytuj fakturę</a>
</div>


<table>
  <tr>
    <th>Klient</th>
    <td>{{ object.customer.company|default_if_none:object.customer.name }}
      <a href="{% url 'invoices:customer-detail' object.customer.pk %}">[dane]</a>
    </td>
    <th>Data wystawienia</th>
    <td>{{ object.issued }}</td>
  </tr>
  <tr>
    <th>Miejsce wydania</th>
    <td>{{ object.get_issue_place_display }}</td>
    <th>Data sprzedaży</th>
    <td>{{ object.transaction }}</td>
  </tr>
  <tr>
    <th>Sposób płatności</th>
    <td>{{ object.get_payment_display }}</td>
    <th>Termin płatności</th>
    <td>{{ object.due }}</td>
  </tr>
</table>

{% if items %}

<table id="invoice-items">

  <tr>
    <th>lp.</th>
    <th>nazwa towaru</th>
    <th>ilość</th>
    <th>stawka VAT</th>
    <th>cena brutto</th>
    <th></th>
    <th></th>
  </tr>
  
  {% for item in items %}
  <tr>
    <td>{{ forloop.counter }}</td>
    <td>{{ item.make.name }}</td>
    <td>{{ item.qty }}</td>
    <td>{{ item.vat }}</td>
    <td>{{ item.price }}</td>
    <td><a href="{% url 'invoices:invoice-item-update' item.pk %}">zmień</a></td>
    <td><a href="{% url 'invoices:invoice-item-delete' item.pk %}">usuń</a></td>
  </tr>
  {% endfor %}

  <tr>
    <td></td>
    <td></td>
    <td></td>
    <th>razem:</th>
    <td>{{ total.sum|floatformat:2 }}</td>
  </tr>
</table>

{% endif %} {# items #}

<form action="{% url 'invoices:invoice-item-create' object.pk %}" method="post">
  <div class="inline">
    <ul>
      {% csrf_token %}
      {{ form.as_ul }}
      <li><label>&nbsp;</label><input class="button-primary" name="" type="submit" value="dodaj"/></li>
    </ul>
  </div>
</form>

{% if items %}
<a class="button white bg-orange" href="{% url 'invoices:latex' object.pk %}">drukuj fakturę</a>
{% endif %}
  

<div class="row">
  <div class="twelve columns">
    <a class="" href="{% url 'invoices:delete' object.pk %}">usuń fakturę</a>
  </div>
</div>

{% endif %} {# object #}

{% endblock %}

templates/invoices/index.html
{% extends 'invoices/base_invoices.html' %}
{% load static %}
{% block title %}faktury{% endblock %}

{% block body %}

{% if object_list %}

<table>

  <tr>
    <th>number faktury</th>
    <th>data wystawienia</th>
    <th>klient</th>
    <th></th>
  </tr>
  
  {% for item in object_list %}

  <tr>
    <td>{{ item.number }}</td>
    <td>{{ item.issued }}</td>
    <td>{{ item.customer.company|default_if_none:"" }} {{ item.customer.name|default_if_none:"" }}</td>
    <td><a href="{% url 'invoices:detail' item.pk %}">wybierz</a></td>
  </tr>
  
  {% endfor %}

</table>

{% endif %}

{% endblock %}

templates/invoices/invoice_item_create.html
{% extends 'invoices/base_invoices.html' %}
{% load static %}
{% block title %}faktury{% endblock %}

{% block body %}

<form action="" method="post">

  {% csrf_token %}
  {{ form.as_p }}

  <div>
    <input name="" type="submit" value="dodaj"/>
  </div>
  
</form>

{% endblock %}