gold/urls.py
from django.urls import path
from django.http import HttpResponse
#from django.contrib.auth.views import LoginView, LogoutView

from . import views


app_name = 'gold'

urlpatterns = [
    path('', views.contract_view, name='form'),
]

inventory/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

app_name = 'inventory'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('search/', views.ItemSearch.as_view(), name='item_search'),
    path('add/', views.ItemCreate.as_view(), name='create'),
    path('<int:pk>/update/', views.ItemUpdate.as_view(), name='update'),
    path('<int:pk>/delete/', views.ItemDelete.as_view(), name='delete'),
    path('inventory/add/', views.InventoryCreate.as_view(),
         name='inventory_create'),
    path('inventory/select/', views.inventory_select, name='inventory_select'),
    path('shelf/reset', views.shelf_reset, name='shelf_reset'),
    path('stats/', views.Stats.as_view(), name='stats'),
    path('latex/', views.latex, name='latex'),
    path('register/', views.register, name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

invoices/urls.py
from django.urls import path

from . import views

app_name = 'invoices'

urlpatterns = [
    # Invoices
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.InvoiceDetailView.as_view(), name='detail'),
    path('<int:customer>/add/', views.InvoiceCreateView.as_view(),
         name='create'),
    path('<int:pk>/update/', views.InvoiceUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.InvoiceDeleteView.as_view(), name='delete'),
    # Invoice Item
    path('item/<int:invoice>/add/', views.InvoiceItemCreateView.as_view(),
         name='invoice-item-create'),
    path('item/<int:pk>/update/', views.InvoiceItemUpdateView.as_view(),
         name='invoice-item-update'),
    path('item/<int:pk>/delete/', views.InvoiceItemDeleteView.as_view(),
         name='invoice-item-delete'),
    # Customers
    path('customer/', views.CustomerIndexView.as_view(),
         name='customer-index'),
    path('customer/<int:pk>/', views.CustomerDetailView.as_view(),
         name='customer-detail'),
    path('customer/add/', views.CustomerCreateView.as_view(),
         name='customer-create'),
    path('customer/<int:pk>/update/', views.CustomerUpdateView.as_view(),
         name='customer-update'),
    path('customer/<int:pk>/delete/', views.CustomerDeleteView.as_view(),
         name='customer-delete'),
    # Generate an invoice
    path('latex/<int:invoice>/', views.latex, name='latex'),
    # path('', views.as_view(), name=''),
]

machines/urls.py
from django.urls import path
from . import views

app_name = 'machines'

urlpatterns = [
    path('', views.MachineIndex.as_view(), name='index'),
    path('<int:pk>/', views.MachineDetail.as_view(), name='detail'),
    path('add/', views.MachineCreate.as_view(), name='create'),
    path('<int:pk>/update/', views.MachineUpdate.as_view(), name='update'),
    path('<int:pk>/del/', views.MachineDelete.as_view(),
         name='delete'),
    path('upload/', views.MachineSetupUpload.as_view(),
         name='setup-upload'),
    path('service/', views.ServiceIndexView.as_view(), name='service_index'),
    path('service/add/', views.ServiceCreate.as_view(), name='service_create'),
    path('service/<int:pk>/del/', views.ServiceDelete.as_view(),
         name='service_delete'),
    path('service/<int:pk>/update/', views.ServiceUpdate.as_view(),
         name='service_update'),
    path('device/', views.DeviceIndexView.as_view(), name='device_index'),
    path('device/<int:pk>/', views.DeviceDetailView.as_view(),
         name='device_detail'),
    path('device/add/', views.DeviceCreate.as_view(), name='device_create'),
    path('device/<int:pk>/del/', views.DeviceDelete.as_view(),
         name='device_delete'),
    path('device/<int:pk>/update/', views.DeviceUpdate.as_view(),
         name='device_update'),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="pl">
  <head>
    <meta charset="UTF-8"/>
    <title>Domino - {% block title %}{% endblock %}</title>
    <meta name="Author" content="Dominik Szmek" />
    <meta name="Copyright" content="Domino" />
    <meta name="Robots" content="noindex, nofollow" />
    <meta name="Language" content="pl" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}" type="text/css" /> 
    <link rel="stylesheet" href="{% static 'css/skeleton.css' %}" type="text/css" /> 
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" /> 

  </head>
  <body>
    <div class="container">

      <!-- project menu -->
      
      <div class="row">
        <div class="left nine columns" id="navbar-main">
          <ul>
            <li><a href="{% url 'inventory:index' %}">remanent</a></li>
            <li><a href="{% url 'invoices:customer-index' %}">faktury</a></li>
            <li><a href="{% url 'gold:form' %}">złoto</a></li>
            <li><a href="{% url 'machines:index' %}">sprzęt</a></li>
            <li><a href="{% url 'admin:index' %}">admin</a></li>

          </ul>
        </div>
        <div class="right three columns" id="navbar-main">
          <ul>
            {% if user.is_authenticated %}
                <li>
                    <strong>{{ user.username }}</strong>
                    <form style="display: inline" method="post" id="logout" action="{% url 'logout' %}">
                        {% csrf_token %}
                        <a onclick="document.getElementById('logout').submit()" style="cursor: pointer">
                            <span>wyloguj</span>
                            <img class="ico" alt="logout" src="{% static 'icons/account-logout.svg' %}"/>
                        </a>
                    </form>
                </li>
            {% endif %}
          </ul>
        </div>
      </div>

      <!-- menu -->
      
      {% block navbar %}{% endblock %}

      <!-- body -->

      {% block body %}{% endblock %}

    </div>
    <footer>
        <div class="container">
            <div class="row">
                <div class="grey">Django version {{ django_version }}</div>
            </div>
        </div>
    </footer>
  </body>
</html>